### ISSUE TITLE
Study possibilities of Apache POI

### ISSUE THREAD

**Issue by cyChop** [KeyboardPlaying/xls-time-tracker-construct#8]
URL: https://poi.apache.org/

* [x] #4 Sheet metadata anonymization
* [x] #5 Reset sheet range on construction
* [x] #6 Generate the sheet from sample lines

**Comment by cyChop** [comment]
The library is a go.
